language: cpp

os:
  - linux

dist: xenial
sudo: false

git:
  depth: 1

branches:
  only:
    - master

env:
  matrix:
    - BUILD_TYPE=Release

addons:
  apt:
    packages:
      - opencv

compiler:
  - gcc
  - clang

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=../install ..
  - make install
